spring:
  mail:
    host: smtp.163.com
    port: 25
    username: shiniandate@163.com
    password:

    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
      smtp:
      auth: true
      timeout: 25000