spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.26.112:3306/metadata_db?userUnicode=true&characterEncoding=UTF-8&userSSL=false
    username: root
    password: 123@gla.net.cn